#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include "shuzagram/domain/user.hpp"
#include "shuzagram/domain/user_errors.hpp"
#include "shuzagram/mtproto/tl_buffer.hpp"

// TL structs for users.getUsers. Every constructor id, flag bit and field
// order below is copied directly from the real wire format generated by
// gotd/td (github.com/iamxvbaba/td@v1.3.3, tg/tl_{user,user_status,
// user_profile_photo,emoji_status,peer_color,restriction_reason,input_user,
// users_get_users}_gen.go) -- the same library the real ShuzaGram Go server
// (/opt/ShuzaGram) links against, so this is byte-for-byte what a real
// client already knows how to parse.
//
// The `user#b1b8cc83` constructor itself has far more optional fields than
// are ported here (bot_nochats, min, bot_inline_geo, apply_min_photo,
// bot_attach_menu, attach_menu_enabled, bot_can_edit, stories_hidden/
// unavailable, contact_require_premium, bot_has_main_app, the whole
// bot_forum_*/bot_can_manage_bots/bot_guestchat/bot_guard family,
// bot_active_users, send_paid_messages_stars, usernames vector,
// stories_max_id, bot_inline_placeholder, lang_code) -- EncodeUser below
// only emits the subset the real Go projection (internal/rpc/convert_users.go
// tgUser/tgSelfUser) ever actually sets. Anything else is a faithful gap,
// not an invented shortcut: see NOTES/users-get-users-plan.md.
namespace shuzagram::mtproto::messages {

// --- InputUser (client -> server) ---

// inputUserEmpty#b98886cf = InputUser;
// inputUserSelf#f7c1b13f = InputUser;
// inputUser#f21158c6 user_id:long access_hash:long = InputUser;
// inputUserFromMessage#1da448e2 peer:InputPeer msg_id:int user_id:long = InputUser;
//
// inputUserFromMessage is never decoded (throws NotImplementedError): its
// business meaning (resolve a user_id mentioned in a specific message the
// peer already forwarded) needs the message-search subsystem, which isn't
// ported yet.
struct InputUser {
    enum class Kind { Empty, SelfUser, ById };
    Kind kind = Kind::Empty;
    std::int64_t user_id = 0;
    std::int64_t access_hash = 0;

    static InputUser Decode(TLBuffer& b) {
        static constexpr std::uint32_t kEmptyId = 0xb98886cf;
        static constexpr std::uint32_t kSelfId = 0xf7c1b13f;
        static constexpr std::uint32_t kByIdId = 0xf21158c6;
        static constexpr std::uint32_t kFromMessageId = 0x1da448e2;

        const std::uint32_t id = b.PeekID();
        if (id == kEmptyId) {
            b.ConsumeID(id);
            return InputUser{};
        }
        if (id == kSelfId) {
            b.ConsumeID(id);
            InputUser in;
            in.kind = Kind::SelfUser;
            return in;
        }
        if (id == kByIdId) {
            b.ConsumeID(id);
            InputUser in;
            in.kind = Kind::ById;
            in.user_id = b.Long();
            in.access_hash = b.Long();
            return in;
        }
        if (id == kFromMessageId) {
            throw domain::NotImplementedError("inputUserFromMessage");
        }
        throw UnexpectedIdError(id);
    }
};

// users.getUsers#0d91a548 id:Vector<InputUser> = Vector<User>;
struct UsersGetUsersRequest {
    static constexpr std::uint32_t kTypeId = 0x0d91a548;
    std::vector<InputUser> ids;

    void DecodeBare(TLBuffer& b) {
        const auto count = b.VectorHeader();
        ids.clear();
        ids.reserve(static_cast<std::size_t>(count));
        for (std::int32_t i = 0; i < count; ++i) {
            ids.push_back(InputUser::Decode(b));
        }
    }
};

// --- User (server -> client) ---

namespace detail {

inline std::vector<std::uint8_t> ToBytes(const std::string& s) { return {s.begin(), s.end()}; }

// userStatusEmpty#009d5c5d / userStatusOnline#edb93949 expires:int /
// userStatusOffline#8c703f was_online:int / userStatusRecently#7b197dc8
// flags:# / userStatusLastWeek#541a1d1a flags:# / userStatusLastMonth#65899777
// flags:# -- the three flags:#-only variants never carry by_me (this port's
// ApproximateUserStatus never sets it), so their flags word is always 0.
inline void EncodeUserStatus(TLBuffer& b, const domain::UserStatus& status) {
    switch (status.kind) {
        case domain::UserStatusKind::Online:
            if (status.expires > 0) {
                b.PutID(0xedb93949);
                b.PutInt32(status.expires);
                return;
            }
            break;
        case domain::UserStatusKind::Offline:
            if (status.was_online > 0) {
                b.PutID(0x8c703f);
                b.PutInt32(status.was_online);
                return;
            }
            break;
        case domain::UserStatusKind::LastWeek:
            b.PutID(0x541a1d1a);
            b.PutUint32(0);
            return;
        case domain::UserStatusKind::LastMonth:
            b.PutID(0x65899777);
            b.PutUint32(0);
            return;
        case domain::UserStatusKind::Empty:
            b.PutID(0x009d5c5d);
            return;
        case domain::UserStatusKind::Recently:
        case domain::UserStatusKind::Unknown:
            break;
    }
    b.PutID(0x7b197dc8); // userStatusRecently
    b.PutUint32(0);
}

// userProfilePhotoEmpty#4f11bae1 = UserProfilePhoto;
// userProfilePhoto#82d1f706 flags:# has_video:flags.0?true photo_id:long
//   stripped_thumb:flags.1?bytes dc_id:int personal:flags.2?true = UserProfilePhoto;
inline void EncodeUserProfilePhoto(TLBuffer& b, const domain::User& u) {
    if (u.photo_id == 0) {
        b.PutID(0x4f11bae1);
        return;
    }
    constexpr std::uint32_t kFlagHasVideo = 1u << 0;
    constexpr std::uint32_t kFlagStrippedThumb = 1u << 1;
    constexpr std::uint32_t kFlagPersonal = 1u << 2;
    std::uint32_t flags = 0;
    if (u.photo_has_video) flags |= kFlagHasVideo;
    if (!u.photo_stripped.empty()) flags |= kFlagStrippedThumb;
    if (u.photo_personal) flags |= kFlagPersonal;

    b.PutID(0x82d1f706);
    b.PutUint32(flags);
    b.PutLong(u.photo_id);
    if (!u.photo_stripped.empty()) b.PutBytes(u.photo_stripped);
    b.PutInt32(u.photo_dc_id);
}

// peerColor#b54b5acf flags:# color:flags.0?int background_emoji_id:flags.1?long = PeerColor;
//
// Matches the real Go SetFlags exactly: bit0 keys off color != 0, not off a
// separate "has color" marker -- an explicit color 0 (domain::PeerColor's
// own has_color) is therefore indistinguishable on the wire from "unset",
// same as upstream (color index 0 is the client's own default anyway).
inline bool EncodePeerColorIfPresent(TLBuffer& b, const domain::PeerColor& color) {
    if (color.Empty()) return false;
    constexpr std::uint32_t kFlagColor = 1u << 0;
    constexpr std::uint32_t kFlagBackgroundEmoji = 1u << 1;
    std::uint32_t flags = 0;
    if (color.has_color && color.color != 0) flags |= kFlagColor;
    if (color.background_emoji_id != 0) flags |= kFlagBackgroundEmoji;

    b.PutID(0xb54b5acf);
    b.PutUint32(flags);
    if (flags & kFlagColor) b.PutInt32(color.color);
    if (flags & kFlagBackgroundEmoji) b.PutLong(color.background_emoji_id);
    return true;
}

// emojiStatusEmpty#2de11aae = EmojiStatus;
// emojiStatus#e7ff068a document_id:long until:flags.0?int = EmojiStatus;
// emojiStatusCollectible#7184603b collectible_id:long document_id:long
//   title:string slug:string pattern_document_id:long center_color:int
//   edge_color:int pattern_color:int text_color:int until:flags.0?int = EmojiStatus;
inline void EncodeEmojiStatus(TLBuffer& b, const domain::UserEmojiStatus& status) {
    if (!status.Valid() || status.Empty()) {
        b.PutID(0x2de11aae);
        return;
    }
    if (!status.collectible.Empty()) {
        const auto& c = status.collectible;
        b.PutID(0x7184603b);
        b.PutUint32(status.until != 0 ? 1u : 0u);
        b.PutLong(c.collectible_id);
        b.PutLong(c.document_id);
        b.PutBytes(ToBytes(c.title));
        b.PutBytes(ToBytes(c.slug));
        b.PutLong(c.pattern_document_id);
        b.PutInt32(c.center_color);
        b.PutInt32(c.edge_color);
        b.PutInt32(c.pattern_color);
        b.PutInt32(c.text_color);
        if (status.until != 0) b.PutInt32(status.until);
        return;
    }
    b.PutID(0xe7ff068a);
    b.PutUint32(status.until != 0 ? 1u : 0u);
    b.PutLong(status.document_id);
    if (status.until != 0) b.PutInt32(status.until);
}

// restrictionReason#d072acb4 platform:string reason:string text:string = RestrictionReason;
//
// Matches applyTgUserRestrictionFields: a reason missing any of the three
// strings is dropped entirely, not encoded with empty strings.
inline std::vector<domain::UserRestrictionReason> ValidRestrictionReasons(const domain::User& u) {
    std::vector<domain::UserRestrictionReason> out;
    for (const auto& r : u.restriction_reasons) {
        if (r.platform.empty() || r.reason.empty() || r.text.empty()) continue;
        out.push_back(r);
    }
    return out;
}

} // namespace detail

// user#b1b8cc83 -- see the file-level comment for exactly which of its many
// optional fields this port ever emits. is_self controls only the `self`
// flag bit: both an explicit inputUserSelf AND an ordinary inputUser naming
// the caller's own id must set it (see ResolveGetUsers), matching Go's
// tgSelfUser/tgUser split.
inline void EncodeUser(TLBuffer& b, const domain::User& u, bool is_self, std::int64_t now) {
    using namespace detail;

    if (u.deleted) {
        // tgUser/tgSelfUser's deleted branch: only id + deleted, deliberately
        // NOT access_hash (see convert_users.go). The frozen bot_verification_icon
        // overlay (applyFrozenUserMark) isn't ported -- nothing in this port yet
        // sets frozen_for_viewer, so that flags2 bit never has a value to emit.
        constexpr std::uint32_t kFlagDeleted = 1u << 13;
        b.PutID(0xb1b8cc83);
        b.PutUint32(kFlagDeleted);
        b.PutUint32(0); // flags2
        b.PutLong(u.id);
        return;
    }

    constexpr std::uint32_t kFlagAccessHash = 1u << 0;
    constexpr std::uint32_t kFlagFirstName = 1u << 1;
    constexpr std::uint32_t kFlagLastName = 1u << 2;
    constexpr std::uint32_t kFlagUsername = 1u << 3;
    constexpr std::uint32_t kFlagPhone = 1u << 4;
    constexpr std::uint32_t kFlagPhoto = 1u << 5;
    constexpr std::uint32_t kFlagStatus = 1u << 6;
    constexpr std::uint32_t kFlagBot = 1u << 14; // doubles as "bot_info_version present"
    constexpr std::uint32_t kFlagRestricted = 1u << 18; // doubles as "restriction_reason present"
    constexpr std::uint32_t kFlagSelf = 1u << 10;
    constexpr std::uint32_t kFlagContact = 1u << 11;
    constexpr std::uint32_t kFlagMutualContact = 1u << 12;
    constexpr std::uint32_t kFlagVerified = 1u << 17;
    constexpr std::uint32_t kFlagSupport = 1u << 23;
    constexpr std::uint32_t kFlagScam = 1u << 24;
    constexpr std::uint32_t kFlagFake = 1u << 26;
    constexpr std::uint32_t kFlagPremium = 1u << 28;
    constexpr std::uint32_t kFlagEmojiStatus = 1u << 30;

    constexpr std::uint32_t kFlag2CloseFriend = 1u << 2;
    constexpr std::uint32_t kFlag2Color = 1u << 8;
    constexpr std::uint32_t kFlag2ProfileColor = 1u << 9;
    constexpr std::uint32_t kFlag2BotBusiness = 1u << 11;
    constexpr std::uint32_t kFlag2LinkedCommunity = 1u << 21;

    const auto reasons = ValidRestrictionReasons(u);
    const bool premium_active = u.PremiumActiveAt(now);
    const bool emoji_status_active = u.EmojiStatusActiveAt(now);

    std::uint32_t flags = 0;
    if (is_self) flags |= kFlagSelf;
    if (u.contact) flags |= kFlagContact;
    if (u.mutual) flags |= kFlagMutualContact;
    if (u.bot) flags |= kFlagBot;
    if (u.verified) flags |= kFlagVerified;
    if (!reasons.empty()) flags |= kFlagRestricted;
    if (u.support) flags |= kFlagSupport;
    if (u.scam) flags |= kFlagScam;
    if (u.fake) flags |= kFlagFake;
    if (premium_active) flags |= kFlagPremium;
    if (u.access_hash != 0) flags |= kFlagAccessHash;
    if (!u.first_name.empty()) flags |= kFlagFirstName;
    if (!u.last_name.empty()) flags |= kFlagLastName;
    if (!u.username.empty()) flags |= kFlagUsername;
    if (!u.bot && !u.phone.empty()) flags |= kFlagPhone; // applyTgUserBotFields clears phone for bots
    flags |= kFlagPhoto; // always encoded (empty variant when no photo)
    if (!u.bot) flags |= kFlagStatus; // bots carry no presence status at all
    if (emoji_status_active) flags |= kFlagEmojiStatus;

    std::uint32_t flags2 = 0;
    if (u.close_friend) flags2 |= kFlag2CloseFriend;
    if (u.bot) flags2 |= kFlag2BotBusiness; // no system-user exemption ported yet
    if (!u.color.Empty()) flags2 |= kFlag2Color;
    if (!u.profile_color.Empty()) flags2 |= kFlag2ProfileColor;
    if (u.linked_community_id != 0) flags2 |= kFlag2LinkedCommunity;

    b.PutID(0xb1b8cc83);
    b.PutUint32(flags);
    b.PutUint32(flags2);
    b.PutLong(u.id);
    if (flags & kFlagAccessHash) b.PutLong(u.access_hash);
    if (flags & kFlagFirstName) b.PutBytes(ToBytes(u.first_name));
    if (flags & kFlagLastName) b.PutBytes(ToBytes(u.last_name));
    if (flags & kFlagUsername) b.PutBytes(ToBytes(u.username));
    if (flags & kFlagPhone) b.PutBytes(ToBytes(u.phone));
    if (flags & kFlagPhoto) EncodeUserProfilePhoto(b, u);
    if (flags & kFlagStatus) EncodeUserStatus(b, u.status);
    if (flags & kFlagBot) b.PutInt32(u.bot_info_version > 0 ? u.bot_info_version : 1);
    if (flags & kFlagRestricted) {
        b.PutVectorHeader(static_cast<std::int32_t>(reasons.size()));
        for (const auto& r : reasons) {
            b.PutID(0xd072acb4);
            b.PutBytes(ToBytes(r.platform));
            b.PutBytes(ToBytes(r.reason));
            b.PutBytes(ToBytes(r.text));
        }
    }
    // bot_inline_placeholder (bit19), lang_code (bit22): never set.
    if (flags & kFlagEmojiStatus) EncodeEmojiStatus(b, u.EmojiStatus());
    // usernames (flags2 bit0), stories_max_id (flags2 bit5): never set.
    if (flags2 & kFlag2Color) EncodePeerColorIfPresent(b, u.color);
    if (flags2 & kFlag2ProfileColor) EncodePeerColorIfPresent(b, u.profile_color);
    // bot_active_users (flags2 bit12), bot_verification_icon (flags2 bit14),
    // send_paid_messages_stars (flags2 bit15): never set.
    if (flags2 & kFlag2LinkedCommunity) b.PutLong(u.linked_community_id);
}

} // namespace shuzagram::mtproto::messages
